### PR TITLE
🏷️: bump to rc2 for new release to trigger release workflow

### PR DESCRIPTION
**Pull request by schlich**

### CODE REVIEW

**Comment by MrCordeiro** [comment]
Is this bump needed? A new release via GitHub Release will also create a new tag. So both triggers would work.

**Comment by schlich** [comment]
the v4.0.0rc1 tag was already made with the first attempt at a release candidate (release workflow failed) -- the new GitHub release tag would have to be rc2.  We could make the release rc2 on GitHub and rc1 on pyPI but that doens't make any sense.

**Comment by schlich** [comment]
@MrCordeiro let me know if that makes sense i'll wait to merge this time.

**Comment by schlich** [comment]
I guess I might be mistaken that you can't edit the tag on the GitHub Release. It seems like in the UI that the platform lets you edit it.  If that's the case then you might be right and we can try that route.

**Comment by schlich** [comment]
PS it looks like i tagged the wrong commit in my terminal because i had forgotten that GH tags releases for us -- that was my mistake. And why i'm test running with release candidate. I tried to be careful; not sure how i tagged the wrong commit!

**Comment by schlich** [comment]
I'll take your deleted comment as a 'good to go' -- let's touch base tomorrow about the full release; maybe you can handle it @MrCordeiro  so i dont mess it up 😉

**Comment by schlich** [comment]
PS another reason why i'm stumbling a little bit here is that i usually manage releases through [python-semantic-release](https://python-semantic-release.readthedocs.io/en/latest/) which automates much of the process. If i get the time i'd like to submit a PR implementing this to lessen maintenance burden just a little bit but obviously would your sign off @MrCordeiro

**Pull request merged**
