### PR TITLE
Rename admin module

### PR DESCRIPTION
**Pull request by dkirkham**
This is a continuation of https://github.com/jazzband/wagtailmenus/pull/472 to address https://github.com/jazzband/wagtailmenus/issues/459.

In particular, this:
- renames the menu administration module from `modeladmin` to `menuadmin`
- renames test modules with include `modeladmin` to now include `menuadmin`
- updates module paths throughout

### CODE REVIEW

**Review by MrCordeiro — APPROVED** [review]
`menuadmin` is a solid name, IMO! Feel free to rebase and merge this PR.

**Comment by schlich** [comment]
@dkirkham lmk if you need help with the rebasing or if you wanna do the honors yourself!

**Comment by dkirkham** [comment]
Hi @MrCordeiro and @schlich, it shouldn't need a rebase to merge - github says there are no conflicts and I was careful to keep these changes self contained.

**Comment by MrCordeiro** [comment]
Hi, I didn't mean a git rebase. 

What I suggested was this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-commits

It's an option next to GitHub's merge button. There are three options: default, squash merge (it adds a single commit to the main branch) and the rebase PR merge, which is akin to `git merge -ff`

**Comment by dkirkham** [comment]
Ah, thanks for the clarification.

**Pull request merged**
