### PR TITLE
Fix wagtailmenus compatibility issue with Wagtail 3.0 with updates to module paths and supported test version

### PR DESCRIPTION
**Pull request by amajai**
Fix for #421 

This line of code below is causing an error in 3.0.
https://github.com/jazzband/wagtailmenus/blob/8be2790c01688dd3c9ef7298bdebe94575c0a76a/wagtailmenus/views.py#L60 

Added a conditional statement to run the line of code if the version on wagtail is below 3.0.

Since Wagtail 3.0 modules have been reorganized, updating the module paths was required.  Added an ImportError exception to all the wagtail Imports for versions before and after 3.0 to be backward compatible.    

Updated the test version of wagtail.

### CODE REVIEW

**Comment by MrCordeiro** [comment]
Wagtail 2.15 is the latest LTS Version and it will still be supported until 2023. We can't accept a PR that removes such support.

Isn't possible to use ImportError to ensure backwards compatibility?

**Review by MrCordeiro — CHANGES_REQUESTED** [review]
Wagtailmenus has to support all versions of Wagtail with active support from torch box (see list here:https://github.com/wagtail/wagtail/wiki/Release-schedule).

Please reintroduce them to the tox configuration so we can be sure the whole suite is passing and that backwards compatibility is not broken.

**Comment by amajai** [comment]
@MrCordeiro My apologies. I thought since there were major changes to the module location, then it will be okay to no longer support older versions. I should have checked the release the schedule before deciding that. 

I could to try to make it backwards compatible by handling ImportError exception. Will also resolve the tox configuration. Thanks.

**Review by MrCordeiro — CHANGES_REQUESTED** [review]
Thanks for updating the tox file! Now the errors we have to solve are appearing. 
I saw that the first one is importing Page from wagtail.models.

The Wagtail team move the contents of "wagtail.core" to "wagtail" recently (https://github.com/wagtail/wagtail/commit/75cc7da38aa45cf411904b6517e1b6b2701924b2), so that would be a good place to start.

**Review by MrCordeiro — APPROVED** [review]
Hey @amajai, this was great! Thanks!

This is ready to be merged, I feel. 

The only thing missing is to prepare the release version (more details here: https://wagtailmenus.readthedocs.io/en/stable/contributing/packaging_releases.html):

- Updating CHANGELOG.md
- Updating the version number
- Updating the docs (specifically the releases page and the index page (that also mentions which Wagtail versions Wagtailmenus is compatible with).

I can do this on the weekend or you can do it before that, your choice. And then I'll merge it! Thanks again for the help!

**Comment by amajai** [comment]
@amajai Glad to help.! I will start preparing the release version.

**Comment by amajai** [comment]
Hi @MrCordeiro. I await your review and merge of the release version https://github.com/jazzband/wagtailmenus/pull/424. 
Thanks.

**Comment by MrCordeiro** [comment]
Done!

**Pull request closed without merging**
