### PR TITLE
Wagtail 5.2

### PR DESCRIPTION
**Pull request by katdom13**
## [Wagtail 5.2 release notes](https://docs.wagtail.org/en/stable/releases/5.2.html)

Changes:
- Add support for Wagtail 5.2 and Python 3.12, drop support for Django 4.0

### CODE REVIEW

**Review by MrCordeiro — APPROVED** [review]
Looks great! Thanks for the help!

**Review by MrCordeiro — CHANGES_REQUESTED** [review]
Oh, I almost forgot, @katdom13 

Could you also update the docs, please? Namely, this file: `/docs/source/index.rst`

**Comment by katdom13** [comment]
Hi @MrCordeiro ,
This commit updates both the index.rst and README.rst.
https://github.com/jazzband/wagtailmenus/pull/465/commits/002fe7723c5a98689fd0ba9c4f08f324939077f6

Thanks for checking.

**Comment by MrCordeiro** [comment]
Thank _you_, @katdom13 !

**Review by MrCordeiro — APPROVED** [review]

**Pull request merged**
